### ISSUE TITLE
I want to using asp.net odata webapi,Also want to using dynamic service of apb,then ?

### ISSUE THREAD

**Issue by liminany** [aspnetboilerplate/sample-odata#3]
I Want to using asp.net odata webapi,Because I can quering data with linq for desktop
 client app (event other net client). Also I like abp auto expose the webapi application service,it is very easy use for web client.

   The odata webapi controller also can auto expose with crud action,and the apb service also can do this only without linq query, I'm confused about it, Does that these two methods can be integrated?

So,What should I to do ? 

The other question is  the sample-odata support NHibernate?

**Comment by hikalkan** [comment]
Hi,

I start from the last. OData can work with NHibernate as I know, since it just waits an IQueryable. So, you can change it to work with NH, ABP supports it.

OData is ideal for CRUD style APIs. Application services much like remote methods which does an arbitrary operation. For example, an application service may have a method named "CalculateTaxPrice" which gets some product and returns the Tax price. This may not fit well to a CRUD operation.

So, actually it's an architectural decision. You can use any of them or combine them together.

Also, I will try to make application services return IQueryable which can be exposed as OData endpoint. One ABP developer did it, so I will check and implement it later.

**Comment by liminany** [comment]
Tks repply. 
Thie first question,I got it. it's an architectural decision,it's depends on The architectural.
Maybe my description is not very clearly,the crud style action is a sample,also can ba a restfull style service,the asp.net odata webapi supported customs action, so if abp service can Implementation most odata webapi Fefures will be well(ex: client linq style query support,auto expose service).
I heard abp will support IQueryable exposing with odata endpoint,so happy,it's a good Fefure. I will use it in my project.

The odata for NHibernate, I found a project :https://github.com/Pathoschild/webapi.nhibernate-odata. It looks like has bugs for NHibernate,wish help for you.

The last, Tks your help,I will foucs on abp contitue

**Comment by Worthy7** [comment]
@hikalkan Hi, is there a way to just add [QueryEnabled] to an IAppService to enable us to easily serve an OData endpoint?

**Comment by ismcagdas** [comment]
@Worthy7 this is not possible with current ABP.

**Comment by Worthy7** [comment]
Can we make it possible :-) It would be extremely cool and helpful.

**Comment by hikalkan** [comment]
Probably not, because adding [QueryEnabled] to application layer breaks layering. In addition, it may not work since OData requires to derive from it's base class.
We suggest to do that in the web layer as a better practice.

**Comment by Worthy7** [comment]
But you already break layering with your dynamic api

**Comment by Worthy7** [comment]
The specific reason I want do this, is that I am making heavy use of the Specification pattern.
The specs are fantastic, and work very well for
1) Checking an entity meets the spec
2) Searching for all entities that meet the spec.
The problem is, that I cannot use these specs from the client side (And then just use Odata for all GETs).
This means that although I can make an Odata endpoint that returns a generic DTO for an entity, I cannot use the standardized specification system with it.

So I need to build separate functions/endpoints for each and every  spec, which is kind of annoying.

This would be bearable if I could do each endpoint from within one controller, but the current way means having to register and write multiple endpoint controller for each any every type of return DTO. Somewhat annoying.

All I want to really do is add the native concepts of "paging and limits" to the returned lists, because there can be a hell of a lot in my case (millions). So initially, i just want to show the user the latest 10, and then allow them to page through which would call again. Sure we can do this all in DTO land, but OData is a standard....

**Comment by hikalkan** [comment]
Dynamic api feature does not break layering. It does not make application layer depending on the web layer. Think again.

**Comment by hikalkan** [comment]
Why not just writing your OData controllers in standard way, in the web layer? We don't say "OData is not standard, do not use it".

**Comment by Worthy7** [comment]
In that case just including the Odata packages into the application layer does not break layering either right?
I can of course write the complex controllers into the API layer, but it's just so trivial that it would be great if ABP had a shortcut - that's all :-)
